{"name": "test_get_home_page", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/anxiaodong/PycharmProjects/hogwarts-httprun/tests/data/login.csv'", "trace": "self = <tests.test_testcase.TestSingle object at 0x10b9b5a90>\n\n    @allure.story(\"测试4\")\n    def test_get_home_page(self):\n        \"\"\"\n    \n            测试呵呵呵呵\n        \"\"\"\n        single_testcase_yaml = os.path.join(os.path.dirname(__file__), \"api\", \"get_home_page.yml\")\n        result = self.run.run_yml(single_testcase_yaml)\n>       allure.attach.file(\"/Users/anxiaodong/PycharmProjects/hogwarts-httprun/tests/data/login.csv\", \"报告\", allure.attachment_type.CSV)\n\ntest_testcase.py:75: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n../../../my_env/httptunner/lib/python3.6/site-packages/allure_commons/_allure.py:151: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n../../../my_env/httptunner/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n../../../my_env/httptunner/lib/python3.6/site-packages/pluggy/manager.py:92: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n../../../my_env/httptunner/lib/python3.6/site-packages/pluggy/manager.py:86: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\n../../../my_env/httptunner/lib/python3.6/site-packages/allure_pytest/listener.py:214: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n../../../my_env/httptunner/lib/python3.6/site-packages/allure_commons/reporter.py:113: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n../../../my_env/httptunner/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n../../../my_env/httptunner/lib/python3.6/site-packages/pluggy/manager.py:92: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n../../../my_env/httptunner/lib/python3.6/site-packages/pluggy/manager.py:86: in <lambda>\n    firstresult=hook.spec.opts.get(\"firstresult\") if hook.spec else False,\n../../../my_env/httptunner/lib/python3.6/site-packages/allure_commons/logger.py:48: in report_attached_file\n    shutil.copy2(source, destination)\n../../../my_env/httptunner/lib/python3.6/shutil.py:257: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nsrc = '/Users/anxiaodong/PycharmProjects/hogwarts-httprun/tests/data/login.csv'\ndst = '/Users/anxiaodong/PycharmProjects/hogwarts-httprun/tests/report/76c1f7aa-ddd0-4ae5-b57e-1154b8906b78-attachment.csv'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        for fn in [src, dst]:\n            try:\n                st = os.stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n    \n        if not follow_symlinks and os.path.islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc:\nE           FileNotFoundError: [Errno 2] No such file or directory: '/Users/anxiaodong/PycharmProjects/hogwarts-httprun/tests/data/login.csv'\n\n../../../my_env/httptunner/lib/python3.6/shutil.py:120: FileNotFoundError"}, "description": "\n\n            测试呵呵呵呵\n        ", "attachments": [{"name": "报告", "source": "76c1f7aa-ddd0-4ae5-b57e-1154b8906b78-attachment.csv", "type": "text/csv"}, {"name": "log", "source": "c78a33f5-a3f7-4b0c-91d3-bb8fc622aa9e-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "005cf23c-c519-4ed4-b924-9ec9cec4dc72-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "116864fe-8c91-43c0-aa19-4644a33fb3bb-attachment.txt", "type": "text/plain"}], "start": 1576375524675, "stop": 1576375525064, "uuid": "a68247d9-1ca6-47a0-bc64-5bfec83a6090", "historyId": "9c95dab400b4a6de89dedd0371d0cc61", "fullName": "test_testcase.TestSingle#test_get_home_page", "labels": [{"name": "story", "value": "测试4"}, {"name": "feature", "value": "测试接口"}, {"name": "suite", "value": "test_testcase"}, {"name": "subSuite", "value": "TestSingle"}, {"name": "host", "value": "anxiaodongdeMacBook-Pro.local"}, {"name": "thread", "value": "13394-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_testcase"}]}